mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from sistemabio import views

urlpatterns = [
    path("sistemabio/", include("sistemabio.urls")),
   #  path('',views.loggin),
    path("admin/", admin.site.urls),
   # path ("admin/loggin/",views.loggin)

]

mysite/sistemabio/urls.py
from django.urls import path
from . import views
from . import views2f, view3v, view4h


app_name = "sistemabio"
urlpatterns = [
    path("",views.index, name="home"),
    path("home_admin/",views.home_admin, name="home_admin"),
    path("home_usuario/",views.home_usuario, name="home_usuario"),
    path("ingresar_usuario/",views.ingresar_usuario, name="ingresar_usuario"),
    path("registrar_usuario/",views.registrar_usuario, name="registrar_usuario"),

    path("signup/",views.signup, name="signup"),
    path("signin/",views.signin, name="signin"),
    path("logout/",views.signout,name="logout"),
    path("about/",views.about, name="about"),
    path("principal/",views.principal, name="principal"),
    path("perfil_administrador", views.perfil_administrador, name="perfil_administrador"),

    #Inquilinos
    path("inquilinos/",views.inquilinos, name="inquilinos"),
    path("new_inquilino/",views.new_inquilino, name="new_inquilino"),
    path("search_inquilino/",views.search_inquilino, name="search_inquilino"),
    path("detail_inquilino/<int:usuario_id>/",views.detail_inquilino, name ="detail_inquilino"),
    # path("detail_inquilino2/<int:usuario_id>/<int:sesion_idu>/",views.detail_inquilino2, name ="detail_inquilino2"),
    path("darbaja_inquilino/<int:inquilino_id>/", views.darbaja_inquilino, name="darbaja_inquilino"),
    path("edit_inquilino/<int:usuario_id>/", views.edit_inquilino, name="edit_inquilino"),
    path ("reporte", views.reporte, name="reporte"),


    #Biométricos
    path("new_biometricos/", views.new_biometricos, name="new_biometricos"),
    # path("new_biometrico/<int:usuario_id>/", views.new_biometrico, name="new_biometrico"),
    #Datos biométricos
    path("facial/<int:usuario_id>/",views2f.facial, name="facial"),
    path("voz3/<int:usuario_id>/", view3v.voz3,name="voz3"),
    path("huella/<int:usuario_id>/", view4h.huella,name="huella"),

    path("facial_usuario/",views2f.facial_usuario, name="facial_usuario"),
    path("voz_usuario/", view3v.voz_usuario,name="voz_usuario"),
    path("huella_usuario/", view4h.huella_usuario,name="huella_usuario"),

    path("accediste/", views2f.accediste,name="accediste"),


    
] 
   

mysite/sistemabio/models.py
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ap_paterno = models.CharField(max_length=15)
    ap_materno = models.CharField(max_length=15)
    #   user = models.ForeignKey(User)
    curp = models.CharField(max_length=30)
     # domicilio
    piso = models.IntegerField()
     # type: Number,
    departamento = models.IntegerField()
     # type: Number,
    telefono = models.CharField(max_length=10)
     # type: String, models.IntegerField()
    correo = models.EmailField()
    #  type: String,
    fecha_nac = models.DateField()
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_actualizado = models.DateTimeField(auto_now=True)
    # Campos con opciones
    CATALOGO_PERFIL = [
        ('1', 'Usuario Inquilino'),
        ('2', 'Usuario Visitante'),
        ('3', 'Usuario Trabajador'),
    ]
    id_perfil = models.CharField(max_length=2, choices=CATALOGO_PERFIL, default='2')
    # Campos con opciones
    CATALOGO_STATUS = [
        ('1', 'ALTA'),
        ('2', 'BAJA'),
    ]
    id_status = models.CharField(max_length=2, choices=CATALOGO_STATUS, default='3')

    def __str__(self):
        # return "{} {} {}". format(self.nombre, self.ap_paterno, self.ap_materno)
        return f'Id {self.id_usuario} -> {self.nombre} {self.ap_paterno} {self.ap_materno}'


class Sesion(models.Model):
    id_sesion = models.AutoField(primary_key=True)
    # Relacion 1 a muchos, 
    # donde 1 usuario puede tener muchas sesiones 
    # Una sesion solo le pertenece a un usuario
    # Una sesion forzosamente deb permanecer a un usuario
    # por lo que no debe ser valor nulo null=False
    # ni almacenar valores vacios blank=False
    id_usuario = models.ForeignKey(Usuario, 
                                   on_delete=models.CASCADE,
                                   null=False,
                                   blank=False)
    CATALOGO_TIPO_SESION = [
        ('1', 'FACIAL'),
        ('2', 'VOZ'),
        ('3', 'HUELLA'),
    ]
    id_tipo_sesion = models.CharField(max_length=2, choices=CATALOGO_TIPO_SESION)

    # id_tipo_sesion = models.IntegerField(null=False, blank=False, choices=CATALOGO_TIPO_SESION, default='4')
    completado = models.BooleanField(default=False)
    # CATALOGO_STATUS_SESION = [
    #     ('0', 'NO REGISTRADO'),
    #     ('1', 'REGISTRADO'),
    # ]
    # id_status_sesion = models.CharField(max_length=2, choices=CATALOGO_STATUS_SESION, default='0')
    dato = models.BinaryField(editable = True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
      
    def __str__(self):
         return f'{self.id_tipo_sesion}'





# class Usuario_Tipo_Sesion(models.Model):
#     id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     id_tipo_sesion = models.ForeignKey(Usuario_Sesion, on_delete=models.CASCADE)
#     image = models.BinaryField()

#contraseña generada por default[5dias para validar el alta sino se dara de baja]
#ingresa para los metodos de inicio de sesion
#si hay datos en la bd, bienvenidos ingresa tus datos boton siguiente, 
# imagen, huella(en el sensor),voz(frase), guardado entra, los datos que esten completados[palomita]
#omitir en algun tipo de sesion, huella y voz (opcional en registro mas tarde)
# display none, administrador sin editar solo visualiza y( elimina registro de sesion, solo desbloquea el bloqueo ) ocultar botones
# inquilinos vista cambiar por tabla, perfil por usuario_(Detail)
#tabla interna de desbloqueo o bloqueo y actualizacio fexha e id de quien lo hizo
#tabla is sesion de id de usuario fecha de alta, actualizacion id de quien actualizo
# Tbl_tipo_sesion
# Idsesion
# Idusuario
# Idtiposesion
# Dato [huella, foto, audio, contraseña] clob o blob
# Fecha_alta
# Fecha_modificacion
# IdUsuario_modificacion

#  IdDato ( numero de muestra)

mysite/sistemabio/views.py
from django.shortcuts import get_object_or_404, render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
import base64
import os
import errno
#creatiionform
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from ftplib import FTP
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Usuario, Sesion
from .forms import InquilinoForm, SesionForm, ReporteForm 
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from django.http import HttpResponse
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph,Image

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors

#Administrador e Index
def index(request):
     title='Index'
     return render (request,"sistemabio/index2.html",{
          'mytitle':title
     })  
def home_admin(request):
     title='Index Admin'
     return render (request,"sistemabio/index.html",{
          'mytitle':title
     })  
def home_usuario(request):
     title='Index Usuario'
     return render (request,"sistemabio/index3u.html",{
          'mytitle':title
     })

def signup(request):
        if request.method == 'GET':
            print('enviando formulario')
            title='Registrar'
            return render(request,"sistemabio/signup.html",
                         {
                              'mytitle':title,
                              'form':UserCreationForm
                         } ) 
        else:
             if request.POST["password1"] == request.POST["password2"]:
                  #register user
                  try:
                    user = User.objects.create_user(username=request.POST["username"],
                                                    email=request.POST["email"],
                                                    first_name=request.POST["first_name"], 
                                                    last_name=request.POST["last_name"],
                                                   password=request.POST["password1"])
                    user.save()
                    login(request, user)
                    return redirect('/sistemabio/principal/')
                   # return HttpResponse('User creado satisfactoriamente')        
                  except IntegrityError:
                       return render(request, "sistemabio/signup.html",{
                            'error': 'El user ya existe',
                            'form':UserCreationForm
                        } ) 
             messages.error(request,  'Passwords no coinciden')    
             return render(request, "sistemabio/signup.html",{
                            'error': 'Passwords no coinciden',
                            'form':UserCreationForm
                        } )   
 
def signin(request):
         if request.method == "GET":
            title='Iniciar sesion'
            return render(request, "sistemabio/signin.html",{
                'mytitle':title,
                'form':AuthenticationForm
            } )        
         else:
              user = authenticate( request, username=request.POST['username'], password=request.POST['password'])
              if user is None:
                messages.error(request, "Usuario o password es incorrecto")
                return render(request, 'sistemabio/signin.html',{
                    'error': "usuario o password es incorrecto.",
                    'form': AuthenticationForm
                    })

              login(request, user)
              return redirect('/sistemabio/principal/')
            
@login_required
def principal(request):
     title='Principal Administrador'
     return render (request,"sistemabio/principal_2.html",{
          'mytitle':title
     })
@login_required
def signout(request):
     logout(request)
     messages.warning(request,"Estás desconectado ahora. Inicia sesión")
     return redirect('/sistemabio/signin/')
def about(request):
     title='About'
     return render (request,"sistemabio/about.html",{
          'mytitle':title
     })
@login_required
def perfil_administrador(request):
     title='Perfil Administrador'
     return render (request,"sistemabio/perfil.html",{
          'mytitle':title
     })
# Inquiinos
def inquilinos(request):
     inquilinos = Usuario.objects.all().order_by('id_usuario')
     paginator = Paginator(inquilinos, 5)  # Divide los datos en páginas con 5 elementos por página
     page_number = request.GET.get('page')
     try:
         page_obj = paginator.page(page_number)
     except PageNotAnInteger:
         # Si el número de página no es un entero, muestra la primera página
         page_obj = paginator.page(1)
     except EmptyPage:
         # Si la página está fuera de rango (por ejemplo, página 9999), muestra la última página
         page_obj = paginator.page(paginator.num_pages)
     title='Inquilinos'
     sesiones = Sesion.objects.all()
     return render (request,"sistemabio/inquilinos/all-inquilinos.html",{
          'mytitle':title,
          'page_obj': page_obj,
          'sesiones': sesiones
     })

def new_inquilino(request):
     if request.method == "GET":
        form=  InquilinoForm
        return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                      {"form":  InquilinoForm })   
     else:
        # print(request.POST)
        # return render(request, 'sistemabio/inquilinos/new-inquilino.html', {"form":  InquilinoForm})
        # commit=False es para procesar los datos antes de guardar, se usa cuando no tienes todos tus 
        # campos llenos de ese form   new_inquilino = form.save()  new_inquilino.save()
        try:
            form = InquilinoForm(request.POST)
            if form.is_valid():
               
               form.save()
            print("Formulario es ", form.is_valid())
            messages.success(request," El registro ha sido un éxito.")
            inquilino = get_object_or_404(Usuario, nombre=form['nombre'].value())
            print('inquilino: ', inquilino.id_usuario)
            personName = str(inquilino.id_usuario) + inquilino.nombre + inquilino.ap_paterno + inquilino.ap_materno
            print("Nombre de personName es: ", personName)
            dataPath = 'C:/Users/yobis/Desktop/sistemabio/mysite/sistemabio/static/inquilinos'
            personPath = dataPath + '/' + personName
            print("Nombre de carpeta es: ", personPath)
            try:
                 os.mkdir(personPath, mode=0o755)
                 print('Carpeta creada: ',personPath)
            except OSError as e:
                 if e.errno!=errno.EEXIST:
                      raise
            return redirect('/sistemabio/new_biometricos/')

        except ValueError:
            messages.error(request, "Error no se creo el inquilino.")
            return render(request, 'sistemabio/inquilinos/new-inquilino.html', 
                          {"form":  InquilinoForm , 
                           "error": "Error creando el inquilino."})
            
def search_inquilino(request):
     #buscar por tipo de usuario
     busqueda = request.POST.get("buscar")
     print('nusqueda es ',busqueda)
     nombre = request.POST.get("nombre")
     print('nombre es ',nombre)
     piso = request.POST.get("piso")
     print('npiso es ',piso)
     departamento = request.POST.get("departamento")
     print('ndepartamento es ',departamento)
     inquilinos = Usuario.objects.all()
     if busqueda:
        inquilinos = Usuario.objects.filter(
            Q(piso = busqueda) | 
            Q(nombre = busqueda) |
            Q(curp = busqueda) |
            Q(departamento = busqueda)
        ).distinct()  
     if nombre:
        inquilinos = Usuario.objects.filter(
            Q(nombre = nombre) 
        ).distinct()  
        print('nombre des ',nombre)
     if piso:
        inquilinos = Usuario.objects.filter(
            Q(piso = piso) 
        ).distinct() 
        print('npiso des ',piso) 
     if departamento:
        inquilinos = inquilinos.filter(
            Q(departamento = departamento)
        ).distinct() 
        print('ndepartamento des ',departamento)
        print('inquilino es ',inquilinos)


     title='search'
     return render (request,"sistemabio/inquilinos/s-inquilinos.html",{
          'mytitle':title,
          'inquilinos':inquilinos
     })
#     
def detail_inquilino(request, usuario_id):
    title='detail'
    inquilino = get_object_or_404(Usuario,id_usuario=usuario_id)
    sesiones =  Sesion.objects.all().filter(id_usuario_id=usuario_id).values() 
#    sesiones =  Sesion.objects.filter(id_usuario=1).values('id_sesion', 'id_usuario_id', 'id_tipo_sesion', 'completado', 'dato', 'fecha_creacion', 'fecha_actualizacion')
    print('usuario id ', usuario_id)
    print(sesiones)
    print('................')
    python6423 = None  # Valor predeterminado
    for sesion in sesiones:
        if sesion['id_tipo_sesion'] == '1':
     #    print('dato: ',sesion['id_sesion']) para acceder a los campos es con '' dentro de corchetes
          print('=======================')   
          print('dato: ',sesion['dato'])
          pytho = base64.b64encode(sesion['dato'])
          print('-------------------------------')
          # print(pytho)
          python642 = pytho.decode('utf-8')
          print('+++++++++++++++++++++++++++++++++')
          # print(python642)
          datos_div = python642.split()
          i=0
          for dato_div in datos_div:

mysite/sistemabio/templates/sistemabio/inquilinos/all-inquilinos.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
<header class="row" style="position: relative; height: 50vh; width: 100%;">
  <div
        class="col s12 m11 l9 xl8 "
        style="position: absolute; top: 0px; height: 120%; left: 0px; right: 40px; width: 100%;"
      > 
      <img alt="" src="{% static 'sistemabio/img/ba21_2.png' %}"
              style="position: absolute; right: -12px; top: 20%; width: 100%; height:80%"
          >
      <img alt="" src="{% static 'sistemabio/img/ba12_2.png' %}"
              style="position: absolute;  right: -12px; top: 0px; width: 100%; height:90%">
  </div>
  <div class="col s4 hide-on-small-only" 

       style="position: absolute; top: 70%; left: 80%; height: 100%; transform: translate(-50%, -50%); width: 30%;" 
  >
      <h1 class="titulo" style="font-size:40px">
        LISTADO DE <b>INQUILINOS</b>
      </h1>
      <blockquote>
        <h4 class="subtitulo black-text" style="font-size:20px">
          <b>
            Aquí puedes consultar los registros <br /> de los Inquilinos
          </b>
        </h4>
      </blockquote>
  </div>
  <div class=" col s12 m9 l9 xl8 white-text" style="height: 100%; position: absolute; top: 0%; right: 50%;">
    <img alt="" src="{% static 'sistemabio/img/parteba15_2.png' %}" 
    class="responsive-img" style="position: absolute; right: 0px; top: 0px; height: 120%; width: 50%;">
  </div>  
</header>
<br />
<br />
<br />
<div class="row justify-content-end">
  <div class="col-3 align-self-end">
    <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134); border-radius: 20px;"
              href="javascript:window.history.back(); " 
          > 
      <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
      </i>       Regresar              
    </a>
  </div>
</div>

<div class="container p-5">
  <h3 style="font-family: 'Franklin Gothic Medium'">Inquilinos registrados</h3>
  <div class="row justify-content-end">
    <div class="col-3 align-self-center">
      <a class="btn btn-outline-warning text-center" style=" background-image: var(--bs-gradient);border-radius: 20px;"
         href="/sistemabio/new_inquilino" 
      >
        <p style="font-family: 'Franklin Gothic Medium'" >
          Añadir inquilino <i class="material-icons rounded-circle ">person_add</i>
        </p>
      </a>
    </div>
  </div>        
</div>

<div class="container-xl">
  <div class="table-responsive">
      <div class="table-wrapper">
          <table class="table table-bordered table-hover table-warning" >
              <thead>
                  <tr style="border-spacing: 1px;" >
                      <th style="border-spacing: 1px;" >Nombre</th>
                      <th border-left-width: 1px; >Tipo de usuario </th>
                      <th>No. Piso </th>
                      <th>No. Dep</th>
                      <th>Datos biometricos</th>
                      <th>Status</th>
                      <th>Actions _____  </th>
                  </tr>
              </thead>
              <tbody>
                {% for inquilino in page_obj %}
                  <tr>
                      <td><h5>{{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}</h5></td>
                      <td>{{ inquilino.get_id_perfil_display }} </td>
                      <td>{{ inquilino.piso }}</td>
                      <td>{{ inquilino.departamento }}</td>
                      <td>
                      {% for sesion in sesiones %}
                        {% if sesion.id_usuario_id == inquilino.id_usuario %}
                           {{sesion.get_id_tipo_sesion_display}}
                            {% if sesion.completado == True %}
                            <input name="completado" type=checkbox checked onclick="return false;"/>
                            {% else %}  
                            <input name="completado" type=checkbox  onclick="return false;"/>
                            {% endif %}
                          <br> 
                        {% endif %}
                      {% endfor %}
                      <td>{{ inquilino.get_id_status_display}} </td>
                      <td>
                          <a href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class="fas fa-eye" style='font-size:24px;color:rgb(61, 149, 249)'></i>
                          </a>
                          <a href="{% url 'sistemabio:edit_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class='fas fa-pencil-alt' style='font-size:24px;color:rgb(251, 227, 48)'></i>
                          </a>
                          <a href="{% url 'sistemabio:darbaja_inquilino' inquilino.id_usuario %}" style="text-decoration:none">
                            <i class='fas fa-trash-alt' style='font-size:24px;color:red'></i>
                          </a>
                      </td>
                  </tr>
                {% endfor %} 
              </tbody>
          </table>
          <!-- Agrega la paginación -->
          <div class="clearfix">
            <!-- <div class="hint-text">Total de registros es de {{ page_obj.paginator.count }}</div> -->
            <ul class="pagination justify-content-end">
              {% if page_obj.has_previous %}
              <li class="page-item "><a href="?page=1" class="page-link"><i class="fa fa-angle-double-left"></i></a></li>
              <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="fa fa-angle-left"></i></a></li>
              <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.previous_page_number }}</a></li>
              {% endif %}
              <li class="page-item active"><a href="?page={{ page_obj.number }}" class="page-link">{{ page_obj.number }}</a></li>
              {% if page_obj.has_next %}
              <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.next_page_number }}</a></li>
              <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fa fa-angle-right"></i></a></li>
              <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link"><i class="fa fa-angle-double-right"></i></a></li>
              {% endif %}
            </ul>
          </div>

      </div>
  </div>  
</div>
{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/darbaja-inquilino.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}

<br>
<br>

<div class="col-md-8 mx-auto">
    <div class="card">
      <div class="card-header bg-danger text-center" style="--bs-bg-opacity: .7;">
        <h3>Dar de baja Usuario</h3>
      </div>
      <div class="card-body bg-danger p-2" style="--bs-bg-opacity: .3;">
        <form method="POST">
            {% csrf_token %}
            <br>
                <p style="font-size: 20px;"> Desea dar de baja el registro de {{inquilino.nombre}} {{inquilino.ap_paterno}} {{inquilino.ap_materno}} ? </p>
            <br>
            <div class="text-center">
            <button class="btn btn-danger">Sí, dar de baja</button>
            <!-- <a class="btn btn-info" href="{% url 'sistemabio:inquilinos' %}">Cancelar</a> -->
            <a class="btn btn-info" href="javascript:window.history.back(); ">Cancelar</a>
            </div>
        </form>
      </div>
    </div>
</div>



<br>
<br>

{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/delete-inquilino.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}

<br>
<br>

<div class="col-md-8 mx-auto">
    <div class="card">
      <div class="card-header bg-danger text-center" style="--bs-bg-opacity: .7;">
        <h3>Eliminar Usuario</h3>
      </div>
      <div class="card-body bg-danger p-2" style="--bs-bg-opacity: .3;">
        <form method="POST">
            {% csrf_token %}
            <br>
                <p style="font-size: 20px;"> Desea eliminar el registro de {{inquilino.nombre}} {{inquilino.ap_paterno}} {{inquilino.ap_materno}} ? </p>
            <br>
            <div class="text-center">
            <button class="btn btn-danger">Sí, eliminar</button>
            <!-- <a class="btn btn-info" href="{% url 'sistemabio:inquilinos' %}">Cancelar</a> -->
            <a class="btn btn-info" href="javascript:window.history.back(); ">Cancelar</a>
            </div>
        </form>
      </div>
    </div>
</div>



<br>
<br>

{% endblock %} 

mysite/sistemabio/templates/sistemabio/inquilinos/s-inquilinos.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
<header class="row" style="position: relative; height: 50vh; width: 100%;">
  <div
        class="col s12 m11 l9 xl8 "
        style="position: absolute; top: 0px; height: 120%; left: 0px; right: 40px; width: 100%;"
      >
      <img alt="" src="{% static 'sistemabio/img/ba5_1.png' %}" 
              style="position: absolute; right: -12px; top: 20%; width: 100%; height:80%"
          >
      <img alt="" src="{% static 'sistemabio/img/ba6_1.png' %}"
              style="position: absolute;  right: -12px; top: 0px; width: 100%; height:90%">
  </div>
  <div class="col s4 hide-on-small-only" 
      
       style="position: absolute; top: 70%; left: 80%; height: 100%; transform: translate(-50%, -50%); width: 30%;" 
  >
      <h1 class="titulo text-black" style="font-size:40px">
        Buscador DE <b>INQUILINOS</b>
      </h1>
      <blockquote>
        <h4 class="subtitulo black-text" style="font-size:20px">
          <b>
            Aquí puedes buscar los registros <br /> de los Inquilinos por nombre, piso o departamento.
          </b>
        </h4>
      </blockquote>
  </div>

  <div class=" col s12 m9 l9 xl8 white-text" style="height: 100%; position: absolute; top: 0%; right: 50%;">
    <img alt="" src="{% static 'sistemabio/img/parteba12_4.png' %}" 
    class="responsive-img" style="position: absolute; right: 0px; top: 0px; height: 120%; width: 50%;">
  </div>  
</header>
<br />
<br />
<br />
<div class="row justify-content-end">
  <div class="col-3 align-self-end">
    <a class="waves-effect waves-light text-white btn p-2 text-center  " style="background: rgb(29, 240, 134);border-radius: 20px;"
              href="javascript:window.history.back(); "
          > 
      <i class="material-icons  text-white large rounded-circle btn p-2 text-center">arrow_back
      </i>       Regresar              
    </a>
  </div>
</div>
<div class="container p-5">
  <div class="row justify-content-center" >
    <div class="col-8 align-self-center" >
      <div class="container-fluid text-left bg-info p-2" style="--bs-bg-opacity: .5;"> 
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
          method="POST">
          {% csrf_token %}
          <div class="input-group">
            <!-- <input type="text" class="form-control bg-light border-1 small solid rgb(61, 101, 213)" placeholder="Buscar" name="buscar" value="{{ request.POST.buscar }}"> -->
            <input type="text" class="form-control bg-light border-1 small solid rgb(61, 101, 213)" placeholder="Nombre" name="nombre">
            <input type="text" class="form-control bg-light border-3 small solid rgb(61, 101, 213)" placeholder="Piso" name="piso"  >
            <!-- <input type="text" class="form-control bg-light border-3 small solid rgb(61, 101, 213)" placeholder="Curp" name="curp" value="{{ request.POST.curp }}" > -->
            <input type="text" class="form-control bg-light border-3 small solid rgb(61, 101, 213)" placeholder="Departamento" name="departamento" >

           
            <button class="btn btn-success" type="submit">
              <span class="material-symbols-rounded">
                search
              </span>
            </button>                                       
          </div>
          
        </form> 
      </div>                      
    </div>
  </div>
  <div class="row bg-success" style=" border: 0.5px solid rgb(13, 126, 79); margin: 25px 0px; --bs-bg-opacity:.5">
    <div class="container text-center pt-5" style="font-family: 'Franklin Gothic Medium'">
      <h3 class=" text-white">
        Las coincidencias son:
      </h3>
    </div>
  
    {% for inquilino in inquilinos %}
    <div class="col-md-3">
      <br>
      <div class="card" style=" border: 0.3px solid rgb(28, 147, 64);  ">
        <div class="card-body ">
          <div class="d-flex p-1 flex-row-reverse">
            <a  href="{% url 'sistemabio:detail_inquilino' inquilino.id_usuario %}">
              <i class='fas fa-info-circle' style='font-size:30px'></i>
              <!-- <span class="material-symbols-rounded">info</span> -->
            </a> 
          </div>
           Usuario:
          <h4 class="card-title ">
           {{ inquilino.nombre}} {{ inquilino.ap_paterno}} {{ inquilino.ap_materno}}
          </h4>
          <p>Tipo de usuario: {{ inquilino.get_id_perfil_display }}</p>
          <p>Curp: {{ inquilino.curp }} </p>
          <p>No. Piso: {{ inquilino.piso }} </p>
          <p>No. Departamento: {{ inquilino.departamento }} </p>
        </div>
      </div>
        <br>
    </div>
  {% endfor %}
     
  </div>
</div>


{% endblock %} 