mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from sistemabio import views

urlpatterns = [
    path("sistemabio/", include("sistemabio.urls")),
   #  path('',views.loggin),
    path("admin/", admin.site.urls),
   # path ("admin/loggin/",views.loggin)

]

mysite/sistemabio/urls.py
from django.urls import path
from . import views
from . import views2f, view3v, view4h


app_name = "sistemabio"
urlpatterns = [
    path("",views.index, name="home"),
    path("home_admin/",views.home_admin, name="home_admin"),
    path("home_usuario/",views.home_usuario, name="home_usuario"),
    path("ingresar_usuario/",views.ingresar_usuario, name="ingresar_usuario"),
    path("registrar_usuario/",views.registrar_usuario, name="registrar_usuario"),

    path("signup/",views.signup, name="signup"),
    path("signin/",views.signin, name="signin"),
    path("logout/",views.signout,name="logout"),
    path("about/",views.about, name="about"),
    path("principal/",views.principal, name="principal"),
    path("perfil_administrador", views.perfil_administrador, name="perfil_administrador"),

    #Inquilinos
    path("inquilinos/",views.inquilinos, name="inquilinos"),
    path("new_inquilino/",views.new_inquilino, name="new_inquilino"),
    path("search_inquilino/",views.search_inquilino, name="search_inquilino"),
    path("detail_inquilino/<int:usuario_id>/",views.detail_inquilino, name ="detail_inquilino"),
    # path("detail_inquilino2/<int:usuario_id>/<int:sesion_idu>/",views.detail_inquilino2, name ="detail_inquilino2"),
    path("darbaja_inquilino/<int:inquilino_id>/", views.darbaja_inquilino, name="darbaja_inquilino"),
    path("edit_inquilino/<int:usuario_id>/", views.edit_inquilino, name="edit_inquilino"),
    path ("reporte", views.reporte, name="reporte"),


    #Biométricos
    path("new_biometricos/", views.new_biometricos, name="new_biometricos"),
    # path("new_biometrico/<int:usuario_id>/", views.new_biometrico, name="new_biometrico"),
    #Datos biométricos
    path("facial/<int:usuario_id>/",views2f.facial, name="facial"),
    path("voz3/<int:usuario_id>/", view3v.voz3,name="voz3"),
    path("huella/<int:usuario_id>/", view4h.huella,name="huella"),

    path("facial_usuario/",views2f.facial_usuario, name="facial_usuario"),
    path("voz_usuario/", view3v.voz_usuario,name="voz_usuario"),
    path("huella_usuario/", view4h.huella_usuario,name="huella_usuario"),

    path("accediste/", views2f.accediste,name="accediste"),


    
] 
   

mysite/sistemabio/models.py
# Create your models here.
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30)
    ap_paterno = models.CharField(max_length=15)
    ap_materno = models.CharField(max_length=15)
    #   user = models.ForeignKey(User)
    curp = models.CharField(max_length=30)
     # domicilio
    piso = models.IntegerField()
     # type: Number,
    departamento = models.IntegerField()
     # type: Number,
    telefono = models.CharField(max_length=10)
     # type: String, models.IntegerField()
    correo = models.EmailField()
    #  type: String,
    fecha_nac = models.DateField()
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_actualizado = models.DateTimeField(auto_now=True)
    # Campos con opciones
    CATALOGO_PERFIL = [
        ('1', 'Usuario Inquilino'),
        ('2', 'Usuario Visitante'),
        ('3', 'Usuario Trabajador'),
    ]
    id_perfil = models.CharField(max_length=2, choices=CATALOGO_PERFIL, default='2')
    # Campos con opciones
    CATALOGO_STATUS = [
        ('1', 'ALTA'),
        ('2', 'BAJA'),
    ]
    id_status = models.CharField(max_length=2, choices=CATALOGO_STATUS, default='3')

    def __str__(self):
        # return "{} {} {}". format(self.nombre, self.ap_paterno, self.ap_materno)
        return f'Id {self.id_usuario} -> {self.nombre} {self.ap_paterno} {self.ap_materno}'


class Sesion(models.Model):
    id_sesion = models.AutoField(primary_key=True)
    # Relacion 1 a muchos, 
    # donde 1 usuario puede tener muchas sesiones 
    # Una sesion solo le pertenece a un usuario
    # Una sesion forzosamente deb permanecer a un usuario
    # por lo que no debe ser valor nulo null=False
    # ni almacenar valores vacios blank=False
    id_usuario = models.ForeignKey(Usuario, 
                                   on_delete=models.CASCADE,
                                   null=False,
                                   blank=False)
    CATALOGO_TIPO_SESION = [
        ('1', 'FACIAL'),
        ('2', 'VOZ'),
        ('3', 'HUELLA'),
    ]
    id_tipo_sesion = models.CharField(max_length=2, choices=CATALOGO_TIPO_SESION)

    # id_tipo_sesion = models.IntegerField(null=False, blank=False, choices=CATALOGO_TIPO_SESION, default='4')
    completado = models.BooleanField(default=False)
    # CATALOGO_STATUS_SESION = [
    #     ('0', 'NO REGISTRADO'),
    #     ('1', 'REGISTRADO'),
    # ]
    # id_status_sesion = models.CharField(max_length=2, choices=CATALOGO_STATUS_SESION, default='0')
    dato = models.BinaryField(editable = True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
      
    def __str__(self):
         return f'{self.id_tipo_sesion}'





# class Usuario_Tipo_Sesion(models.Model):
#     id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
#     id_tipo_sesion = models.ForeignKey(Usuario_Sesion, on_delete=models.CASCADE)
#     image = models.BinaryField()

#contraseña generada por default[5dias para validar el alta sino se dara de baja]
#ingresa para los metodos de inicio de sesion
#si hay datos en la bd, bienvenidos ingresa tus datos boton siguiente, 
# imagen, huella(en el sensor),voz(frase), guardado entra, los datos que esten completados[palomita]
#omitir en algun tipo de sesion, huella y voz (opcional en registro mas tarde)
# display none, administrador sin editar solo visualiza y( elimina registro de sesion, solo desbloquea el bloqueo ) ocultar botones
# inquilinos vista cambiar por tabla, perfil por usuario_(Detail)
#tabla interna de desbloqueo o bloqueo y actualizacio fexha e id de quien lo hizo
#tabla is sesion de id de usuario fecha de alta, actualizacion id de quien actualizo
# Tbl_tipo_sesion
# Idsesion
# Idusuario
# Idtiposesion
# Dato [huella, foto, audio, contraseña] clob o blob
# Fecha_alta
# Fecha_modificacion
# IdUsuario_modificacion

#  IdDato ( numero de muestra)

mysite/sistemabio/forms.py
from django.forms import ModelForm
from django import forms
from .models import Usuario, Sesion
from django.db import models
import phonenumbers
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class InquilinoForm(forms.ModelForm): 
    # def clean_telefono(self):
    #     telefono_str = self.cleaned_data.get('telefono')
    #     # codigo_pais= "MX"
    #     try:
    #         # telefono = phonenumbers.parse(telefono_str,codigo_pais)
    #         # if not phonenumbers.is_valid_number(telefono):
    #         #     raise ValidationError("Ingrese un número de teléfono válido")
    #         if telefono_str.isdigit():  # Verifica si es un número
    #             raise ValidationError("Ingrese un número de teléfono válido")
    #         return telefono_str
    #     except phonenumbers.phonenumberutil.NumberParseException as e:
    #         raise ValidationError("Ingrese un número de teléfono válido")
    #     return telefono_str
    class Meta:
        model = Usuario
        fields = ['nombre','ap_paterno','ap_materno', 'curp','piso','departamento','telefono', 'correo', 'fecha_nac', 'id_perfil', 'id_status']
        widtgets={
             'fecha_nac':forms.TextInput(attrs={'class': 'form-control'})
            }
        # acepta fechas aaaa-mm-dd y dd/mm/aaaa pero no aaaa/mm/dd ni dd-mm-aaaa 
    # def validar_email(self):
    #     email = self.cleaned_data.get('email')
    #     if not email.endswith('@example.com'):  # Validación personalizada
    #         raise ValidationError("Ingrese un correo válido con dominio @example.com")
    #     return email

    
        # self.fields['fecha_nac'].widget.attrs[]
    def __init__(self, *args,**kwargs):
        super(InquilinoForm,self).__init__(*args,**kwargs)
        self.fields['nombre'].widget.attrs['class']= 'form-control'
        self.fields['ap_paterno'].widget.attrs['class']= 'form-control'
        self.fields['ap_materno'].widget.attrs['class']= 'form-control'
        self.fields['curp'].widget.attrs['class']= 'form-control'
        self.fields['piso'].widget.attrs['class']= 'form-control'
        self.fields['departamento'].widget.attrs['class']= 'form-control'
        self.fields['telefono'].widget.attrs['class']= 'form-control'
        self.fields['correo'].widget.attrs['class']= 'form-control'
        self.fields['fecha_nac'].widget.attrs['class']= 'form-control'
        self.fields['id_perfil'].widget.attrs['class']= 'form-control'
        self.fields['id_status'].widget.attrs['class']= 'form-control'
        self.fields['ap_paterno'].label= 'Apellido Paterno'
        self.fields['ap_materno'].label='Apellido Materno'
        self.fields['piso'].label='No. Piso'
        self.fields['departamento'].label= 'No. Departamento'
        self.fields['telefono'].label= 'No. Teléfono'
        self.fields['fecha_nac'].label= 'Fecha de Nacimiento'
        self.fields['id_perfil'].label= 'Perfil de Usuario'
        self.fields['id_status'].label= 'Status'
        
                                              
#solo usuario
class SesionForm(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario']
    def __init__(self, *args,**kwargs):
         super(SesionForm,self).__init__(*args,**kwargs)
        # self.fields['id_tipo_sesion'].widget.attrs['class']='form-control'
         self.fields['id_usuario'].widget.attrs['class']= 'form-control'
#solo dato
class ReporteForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['id_perfil' ]
    def __init__(self, *args,**kwargs):
        super(ReporteForm,self).__init__(*args,**kwargs)
        self.fields['id_perfil'].widget.attrs['class']= 'form-control'
        self.fields['id_perfil'].label= 'Indica que tipo de usuario generarás reporte'

class MiFormularioSimple(forms.Form):
  #  dato_simple = forms.CharField('label'='Dato')
    dato_simple = forms.CharField(label='Dato', widget=forms.TextInput(attrs={'class': 'form-control'}))


#todo el modelo facial
class SesionForm3(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario', 'dato','id_tipo_sesion','completado']
        labels = {'completado':'Completo',}
    def __init__(self, *args,**kwargs):
         super(SesionForm3,self).__init__(*args,**kwargs)
         #Widgets son los que se van a pintan en forma de etiquetas html
         self.fields['id_usuario'].widget.attrs['class']= 'form-control' 
         self.fields['id_usuario'].label= 'Usuario'
         self.fields['dato'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].widget.value='1'
         self.fields['id_tipo_sesion'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].label= 'Tipo Session'
         #self.fields['completado'].label= 'Hecho'

#todo el modelo voz
class SesionFormVoz(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario', 'dato','id_tipo_sesion','completado']
        labels = {'completado':'Completo',}
    def __init__(self, *args,**kwargs):
         super(SesionFormVoz,self).__init__(*args,**kwargs)
         #Widgets son los que se van a pintan en forma de etiquetas html
         self.fields['id_usuario'].widget.attrs['class']= 'form-control' 
         self.fields['id_usuario'].label= 'Usuario'
         self.fields['dato'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].widget.value='2'
         self.fields['id_tipo_sesion'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].label= 'Tipo Session'
         #self.fields['completado'].label= 'Hecho'

#todo el modelo huella
class SesionFormHuella(ModelForm):
    class Meta:
        model = Sesion
        fields = ['id_usuario', 'dato','id_tipo_sesion','completado']
        labels = {'completado':'Completo',}
    def __init__(self, *args,**kwargs):
         super(SesionFormHuella,self).__init__(*args,**kwargs)
         #Widgets son los que se van a pintan en forma de etiquetas html
         self.fields['id_usuario'].widget.attrs['class']= 'form-control' 
         self.fields['id_usuario'].label= 'Usuario'
         self.fields['dato'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].widget.value='3'
         self.fields['id_tipo_sesion'].widget.attrs['class']='form-control' 
         self.fields['id_tipo_sesion'].label= 'Tipo Session'
         #self.fields['completado'].label= 'Hecho'

         self.fields['id_tipo_sesion'].label= 'Tipo Session'

mysite/sistemabio/templates/sistemabio/about.html
<!-- My Content -->
{% extends "sistemabio/base_2.html" %}

{% block content %}
    <main
      class="container pt-2 text-center d-flex justify-content-center align-items-center vh-100"
    >
      <section class="card bg-success" style="--bs-bg-opacity: .5;">
        <div class="card-body">
           <h1 class="display-1">About</h1>
            <p> 
                Este es un sistema biométrico para el control de acceso peatonal a un edificio.
                Cuenta con una base de datos escalable y de código abierto; se usa el reconocimiento facial, reconocimiento de voz y reconocimiento de huella digital.
            </p>
        </div>
       </section>
    </main>

{% endblock %}

mysite/sistemabio/templates/sistemabio/facial.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
 <!-- Webcam.min.js-->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.min.js"></script> 
      
    <header class="row" style="position: relative;  height: 50vh; width: 100%;" >
        <div
          class="col s12 m11 l9 xl8 "
          style="position: absolute; top: 0px; height: 60%; left: 0px;"
        >
          <img
            alt="imagen1"
            src="{% static 'sistemabio/img/rec5.png' %}"
            class="responsive-image" 
            style="height: 200%; width: 80%; left: 0px; top: 0px; position: absolute; object-fit: cover;"
          />
        </div>
        <div class="col s12 m9 l9 xl8 white-text" 
             style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
        >
        <br>
              <br>
            <blockquote>
              <br>
              <h2 class="subtitulo black-text ">
                <b>
                  Rostro <br /> 
                </b>
              </h2>
            </blockquote>
        </div>
        
        <div class="col m6 l6 xl5 hide-on-small-only" style="height: 100%; position: absolute; top: 0%; right: 0%;">
          <img alt="" src="{% static 'sistemabio/img/parteba10.png' %}" 
          class="responsive-img" style="position: absolute; right: -5px; top: 0px; height: 100%; width: 50%;">
        </div>  
    </header>
      <br />
      <!--
      <br />
      -->
    
     

<div class="col-md-8 mx-auto">
  <div class="card">
    <div class="card-header bg-success text-center" style="--bs-bg-opacity: .7;">
      <h3 class="text-white">Captura el rostro
        <i class="material-icons small rounded-circle " style="font-size:40px;">face
        </i>
      </h3>
    </div>
    <div class="card-body text-left bg-success "style="--bs-bg-opacity: .3;">
      <form  method="POST" enctype="multipart/form-data" >
        {% csrf_token %} 
       
      <div class="container">
          <div class="row ">
              <div class="col">
                  <p class="text-black" style="font-family: 'Franklin Gothic Medium'; font-size: 20px;" > 
                    <b>Aquí se realiza la captura de rostro</b>
                  </p>
                  <br>
                  <p>
                    Al oprimir el boton de "Take Foto" se tomará una imagen de tu rostro, posterior a eso tendrás que oprimir el botón de aceptar para continuar con el registro.
                  </p>
                  <div class="row justify-content-md-center">
                    <div class="col-6 aling-self-center">
                      <br>
                      <div id="my_camera"></div>
                      <br>
                      <div class="d-flex justify-content-center">
                       <button type="button" class="btn btn-primary" onclick="takeSnapshotAndSend()">Capturar</button> 
                      </div>
                      <br>
                      <div id="results" ></div>
                      <br>

                      <label for="id_usuario">Usuario:</label>
                      <select class="form-control" type="text" id="id_usuario" name="id_usuario" >
                        <option value="{{inquilino.id_usuario}}" selected="selected">Id {{inquilino.id_usuario}} -> {{inquilino.id_usuario}} {{inquilino.nombre}} {{inquilino.ap_paterno}} {{inquilino.ap_materno}}</option>
                      </select readonly>
                      
                      <label for="id_tipo_sesion">Tipo de sesion:</label>
                      <select class="form-control" type="text" id="id_tipo_sesion" name="id_tipo_sesion" >
                        <option value="1" selected="selected">Tipo sesion {{sesion.id_tipo_sesion}} ->FACIAL</option>
                      </select readonly>

                      <label for="id_dato">Dato:</label>
                      <input type="text" name="dato" class="form-control" id="id_dato"/> 
                      
                      <h5></h5>
                      <!-- {{form}} -->
                        
                     <script language="JavaScript">
                       Webcam.set({
                            width: 320, 
                            height: 240,
                            image_format: 'jpeg',
                            jpeg_quality: 90
                        });
                        
                        Webcam.attach('#my_camera');
                        var numPhotos = 50; // Número total de fotos que se van a capturar
                        var photoCounter = 0; // Contador de fotos capturadas
                        const data_uri2 = [];
                        function takeSnapshotAndSend() {
                          for (var i = 0; i <numPhotos; i++) {
                            // Tomar la instantánea y obtener los datos de la imagen
                            Webcam.snap(function(data_uri) {
                              // display results in page
                              document.getElementById('results').innerHTML = 
                              // '<img id="imageprev" src="'+data_uri+'"/>';
                              '<img id="imageprev" src="'+data_uri+'"/>';
                              var valor = document.getElementById("results").innerHTML;
                              // console.log("valor",valor);
                              document.getElementById("id_dato").value = data_uri ;
                              // console.log("dta uri",data_uri);
                              data_uri2.push(' ' + data_uri);
                              // console.log("dta uri2",data_uri2);
                              document.getElementById("id_dato").value = data_uri2 ;
                              // Incrementar el contador de fotos capturadas
                              photoCounter++;
                              // console.log("Foto tomada ", photoCounter)
                            });
                          }
                          console.log("Total de Fotos tomadas ", photoCounter) 
                          // print('array',data_uri2)
                        }
                      </script>
                    </div>                   
                  </div>          
                  <br>
                  <br>                  
              </div>
          </div>
       
            <button class="btn btn-info w-100" type="submit">
              Guardar 
              <i class="material-icons "> save</i>
            </button>
    
         
      
      </div>
      </form>
    </div>
  </div>
</div>
<br>


{% endblock %}

mysite/sistemabio/templates/sistemabio/facial_usuario.html
{% extends "sistemabio/base_2.html" %}
{% load static %}
{% block content %}
 <!-- Webcam.min.js-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.min.js"></script> 
      
<header class="row" style="position: relative;  height: 50vh; width: 100%;" >
  <div
    class="col s12 m11 l9 xl8 "
    style="position: absolute; top: 0px; height: 60%; left: 0px;"
  >
    <img
      alt="imagen1"
      src="{% static 'sistemabio/img/rec5.png' %}"
      class="responsive-image" 
      style="height: 200%; width: 80%; left: 0px; top: 0px; position: absolute; object-fit: cover;"
    />
  </div>
  <div class="col s12 m9 l9 xl8 white-text" 
       style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;"
  >
    <br><br>
    <blockquote>
      <br>
      <h2 class="subtitulo black-text ">
        <b>
          Rostro <br /> 
        </b>
      </h2>
    </blockquote>
  </div>
  <div class="col m6 l6 xl5 hide-on-small-only" style="height: 100%; position: absolute; top: 0%; right: 0%;">
    <img alt="" src="{% static 'sistemabio/img/parteba10.png' %}" 
    class="responsive-img" style="position: absolute; right: -5px; top: 0px; height: 100%; width: 50%;">
  </div>  
</header>
<br />
<div class="col-md-8 mx-auto">
  <div class="card">
    <div class="card-header bg-success text-center" style="--bs-bg-opacity: .7;">
      <h3 class="text-white">Captura el rostro
        <i class="material-icons small rounded-circle " style="font-size:40px;">face
        </i>
      </h3>
    </div>
    <div class="card-body text-left bg-success "style="--bs-bg-opacity: .3;">
      <form  method="POST" enctype="multipart/form-data" >
        {% csrf_token %} 
        <div class="container">
          <div class="row ">
              <div class="col">
                  <p class="text-black" style="font-family: 'Franklin Gothic Medium'; font-size: 20px;" > 
                    <b>Aquí se realiza la captura de rostro</b>
                  </p>
                  <br>
                  <p>
                    Al oprimir el boton de "Take Foto" se tomará una imagen de tu rostro, posterior a eso tendrás que oprimir el botón de aceptar para continuar con el registro.
                  </p>
                  <div class="row justify-content-md-center">
                    <div class="col-6 aling-self-center">
                      <br>
                      <div id="my_camera"></div>
                      <br>
                      <div class="d-flex justify-content-center">
                      <button type="button" class="btn btn-primary" onclick="takeSnapshotAndSend()">Capturar</button> 
                      </div>
                      <br>
                      <div id="results" ></div>
                      <br>
                      {{form}}
                      <!-- <label for="id_dato_simple">Dato:</label>
                      <input type="text" name="dato_simple" class="form-control" id="id_dato_simple"/>  
                   
                       -->
                      <h5></h5>
                        
                    <script language="JavaScript">
                      Webcam.set({
                            width: 320, 
                            height: 240,
                            image_format: 'jpeg',
                            jpeg_quality: 90
                        });
                        
                        Webcam.attach('#my_camera');
                        var photoCounter = 0; // Contador de fotos capturadas
                        function takeSnapshotAndSend() {
                          // Tomar la instantánea y obtener los datos de la imagen
                          Webcam.snap(function(data_uri) {
                            // display results in page
                            document.getElementById('results').innerHTML = 
                            // '<img id="imageprev" src="'+data_uri+'"/>';
                            '<img id="imageprev" src="'+data_uri+'"/>';
                            var valor = document.getElementById("results").innerHTML;
                            console.log("valor",valor);
                            // document.getElementById("id_dato").value = valor ;
                            // console.log("valor2",valor);
                            document.getElementById("id_dato_simple").value = data_uri ;
                            console.log("dta uri",data_uri);
                            data_uri2.push(' ' + data_uri);
                            // Incrementar el contador de fotos capturadas
                            photoCounter++;
                            console.log("Foto tomada ", photoCounter)
                          });
                        }
                      </script>
                    </div>                   
                  </div>          
                  <br>
                  <br>                  
              </div>
          </div>
          <button class="btn btn-info w-100" type="submit">
            Guardar 
            <i class="material-icons "> save</i>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<br>


{% endblock %}

mysite/sistemabio/templates/sistemabio/huella.html
{% extends "sistemabio/base.html" %}
{% load static %}
{% block content %}
 

<header class="row" style="position: relative; height: 50vh; width: 100%;">
  <div class="col s12 m11 l9 xl8 " style="position: absolute; top: 0px; height: 60%; left: 0px;">
    <img alt="imagen1" src="{% static 'sistemabio/img/rec5_1.png' %}" class="responsive-image"
      style="height: 200%; width: 80%; left: 0px; top: 0px; position: absolute; object-fit: cover;" />
  </div>
  <div class="col s12 m9 l9 xl8 white-text"
    style="position: absolute; top: 50%; left: 30%; height: 100%; transform: translate(-50%, -50%); width: 50%;">
    <br>
    <br>
    <blockquote>

      <h2 class="subtitulo black-text ">
        <b>
          HUELLA <br />
        </b>
      </h2>
    </blockquote>
  </div>

  <div class="col m6 l6 xl5 hide-on-small-only" style="height: 100%; position: absolute; top: 0%; right: 0%;">
    <img alt="" src="{% static 'sistemabio/img/parteba12_3.png' %}" class="responsive-img"
      style="position: absolute; right: -5px; top: 0px; height: 120%; width: 80%;">
  </div>
</header>

<br ><br >
<br >
<br ><br >
<br >
<div class="col-md-8 mx-auto">
  <div class="card">
    <div class="card-header bg-success text-center" style="--bs-bg-opacity: .7;">
      <h3 class="text-white">Captura la huella
        <i class="material-icons small rounded-circle " style="font-size:40px;">fingerprint
        </i>
      </h3>
    </div>
    <div class="card-body text-left bg-success " style="--bs-bg-opacity: .3;">
      
      <div class="container">
        <div class="row">
          <div class="col ">
            <p class="text-black" style="font-family: 'Franklin Gothic Medium'; font-size: 20px;">
              <b>Aquí se realiza la captura de la huella</b>
            </p>
            <br>
            <p>
             Tendrás 5 segundos para colocar tu huella del dedo indice derecho en el lector de huella
            </p>
            
             
            <div class="col ">
              <form  method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                <label for="id_usuario">Usuario:</label>
                <select class="form-control" type="text" id="id_usuario" name="id_usuario" >
                  <option value="{{inquilino.id_usuario}}" selected="selected">Id {{inquilino.id_usuario}} -> {{inquilino.id_usuario}} {{inquilino.nombre}} {{inquilino.ap_paterno}} {{inquilino.ap_materno}}</option>
                </select readonly>
                <label for="id_tipo_sesion">Tipo de sesion:</label>
                <select class="form-control" type="text" id="id_tipo_sesion" name="id_tipo_sesion" >
                  <option value="3" selected="selected">Tipo sesion {{sesion.id_tipo_sesion}} ->HUELLA</option>
                </select readonly>
                <label for="id_dato">Dato:</label>
                <input type="text" name="dato" class="form-control" id="id_dato" />
                <br> <br>
                <div>
                  <button class="btn btn-info w-100" type="submit">
                    Guardar 
                    <i class="material-icons "> save</i>
                  </button>
                </div>
            </form>
          </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<br>



<br>
{% endblock %}